# from https://docs.travis-ci.com/user/languages/python/
language: python

python:
  - "2.7"

install:
  - apt-get update -q -y
  - pip install -r requirements.txt
  - pip install tox
script:
  - tox
